spring:
  application:
    name: financial-management-service
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm-name}
          jwk-set-uri: ${keycloak.url}/realms/${keycloak.realm-name}/protocol/openid-connect/certs
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 9013

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetchRegistry: true
  instance:
    hostname: financial-management-service
    prefer-ip-address: true

db:
  name: financial_db
  server-ip: localhost
  username: postgres
  password: Paroli123
  port: 5432
  provider: postgresql
  url: jdbc:postgresql://localhost:5432/financial_db

keycloak:
  server-ip: 10.10.14.19
  server-port: 8080
  realm-name: Netto
  url: http://${keycloak.server-ip}:${keycloak.server-port}

token:
  converter:
    principal-attribute: preferred_username

env:
  service:
    healthcare-provider:
      url: http://10.10.14.19:9007/api/v1/healthcare-provider
    financial-management:
      url: http://localhost:9013


cache:
  otp:
    ttl: 1500

